### ISSUE TITLE
Throwing "ArrayIndexOutOfBoundsException" when converting.

### ISSUE THREAD

**Issue by Porush** [anupthegit/WOFFToTTFJava#1]
Throwing **"ArrayIndexOutOfBoundsException"** when converting **woff** font to **ttf** font. **woff** font is working fine in browser so its unlikely to be corrupted. Also can you add support for **woff2**, **woff** font is barely in use nowadays.

`java.lang.ArrayIndexOutOfBoundsException: length=28; regionStart=-1; regionLength=29`

Thanks

**Comment by anupv-digilab** [comment]
Hey @Porush Is this issue resolved? I saw you closed it so I'm curious

**Comment by Porush** [comment]
@anupv-digilab Yeah, It's solved or at least it works by using unconsumed/unprocessed **byteArray** as **inputStream** in **writeFontData** method.

![IMG_20211018_180054.jpg](https://user-images.githubusercontent.com/17381073/137730901-448277e1-35dd-438b-a317-d5c3874be422.jpg)
